/*
CREATE TABLE CATEGORY_DETAILS(
CATEGORY_ID NUMERIC(2) NOT NULL ,
CATEGORY_NAME VARCHAR(30));

CREATE TABLE SUB_CATEGORY_DETAILS(
SUB_CATEGORY_ID NUMERIC(2) not null,
CATEGORY_ID NUMERIC(2),
SUB_CATEGORY_NAME VARCHAR(30));

CREATE TABLE PRODUCT_DETAILS(
PRODUCT_ID NUMERIC(6) not null,
SUB_CATEGORY_ID NUMERIC(2),
CATEGORY_ID NUMERIC(2),
PRODUCT_NAME VARCHAR(30));

--1
ALTER TABLE CATEGORY_DETAILS ALTER COLUMN CATEGORY_ID NUMERIC(2) NOT NULL;
ALTER TABLE CATEGORY_DETAILS ADD CONSTRAINT PK_CAT PRIMARY KEY(CATEGORY_ID);
--2

--ALTER TABLE SUB_CATEGORY_DETAILS ALTER COLUMN SUB_CATEGORY_ID NUMERIC(2) NOT NULL;
--ALTER TABLE SUB_CATEGORY_DETAILS ADD CONSTRAINT PK_SCAT PRIMARY KEY(SUB_CATEGORY_ID);
--3
--ALTER TABLE SUB_CATEGORY_DETAILS ADD  FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY_DETAILS(CATEGORY_ID);
--4

--ALTER TABLE PRODUCT_DETAILS ALTER COLUMN PRODUCT_ID NUMERIC(2) NOT NULL;
ALTER TABLE PRODUCT_DETAILS ADD CONSTRAINT P_T PRIMARY KEY(PRODUCT_ID) ;
ALTER TABLE PRODUCT_DETAILS ADD FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY_DETAILS(CATEGORY_ID);
ALTER TABLE PRODUCT_DETAILS ADD FOREIGN KEY (SUB_CATEGORY_ID) REFERENCES SUB_CATEGORY_DETAILS(SUB_CATEGORY_ID);
--5
*/
--ALTER TABLE PRODUCT_DETAILS ADD PRICE NUMERIC(2);
--6
--ALTER TABLE PRODUCT_DETAILS ALTER COLUMN PRICE NUMERIC(6,2);
--8
--ALTER TABLE PRODUCT_DETAILS DROP COLUMN PRICE;
--9
--ALTER TABLE PRODUCT_DETAILS ADD BRANDNAME VARCHAR(20) NOT NULL;
--10
--EXEC SP_RENAME 'CATEGORY_DETAILS','CAT_DT';
--*/
select *
from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME='\SUB_CATEGORY_DETAILS';